#!/usr/local/bin/ansible-playbook --inventory=inventory
- name: 'RedHat | TRNO | bundle | artifacts' 
  hosts: containerone
  vars_files:
    - '../p1.yml'
    - 'vars/{{ target_environment }}.yml'
    - 'vars/global.yml'
  vars:
    module: "bundle"
    ansible_name_module: "{{ ansible_name }} | {{ module }}"
    redhat_quay_pull_file: '{{ dir_artifacts }}/.docker/master.json }}'
  roles:
    - bundle
